exclude:
    - "dq_*"
    - "test_seed_*"
    - "cosmos_table"
    - "lookup_check_base"
    - "db_m_*"
    - "zzz_*"
    - "sys.*"
    - "shedlock"
    - "lookup_check_base"
    - "lookup_column"
    - "schema_versioning"
    - "artifact_audit"
    - "bulk_activation_tracker"
    - "bulk_asset_details"
    - "bulk_user_details"
    - "cosmos_table"
    - "feedback_question"
    - "file_processing_tracker"